# Generated by Django 3.0.6 on 2020-06-24 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200623_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='criado_por',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
